### ISSUE TITLE
Crashes when no Playlists exist

### ISSUE THREAD

**Issue by Prior99** [rattboi/mopidy-subsonic#23]
I get the following error when connecting to my server. After I created an empty Playlist the error disappeared:
```
ERROR    Got un-handled exception from SubsonicBackend
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mopidy/commands.py", line 237, in _actor_error_handling
    yield
  File "/usr/lib/python2.7/site-packages/mopidy/commands.py", line 385, in start_backends
    config=config, audio=audio).proxy()
  File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 93, in start
    obj = cls(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/Mopidy_Subsonic-1.0.0-py2.7.egg/mopidy_subsonic/actor.py", line 32, in __init__
    self.playlists = SubsonicPlaylistsProvider(backend=self)
  File "/usr/lib/python2.7/site-packages/Mopidy_Subsonic-1.0.0-py2.7.egg/mopidy_subsonic/playlist.py", line 15, in __init__
    self.playlists = self._get_playlists()
  File "/usr/lib/python2.7/site-packages/Mopidy_Subsonic-1.0.0-py2.7.egg/mopidy_subsonic/playlist.py", line 36, in _get_playlists
    playlists = self.remote.get_user_playlists()
  File "/usr/lib/python2.7/site-packages/Mopidy_Subsonic-1.0.0-py2.7.egg/mopidy_subsonic/client.py", line 522, in get_user_playlists
    for p in results]
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by hhm0** [comment]
See #8.

**Comment by Prior99** [comment]
I [reimplemented the whole thing](https://github.com/Prior99/mopidy-subidy) as it seems kind of unstable. If you want, you may close this issue as it no longer affects me, though it probably still persists.
